name: fgc
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-VariableFont_wght.ttf
    - family: Algerian
      fonts:
        - asset: assets/fonts/alger.TTF
    - family: Bitter
      fonts:
        - asset: assets/fonts/Bitter-VariableFont_wght.TTF
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-VariableFont_wght.TTF
    - family: Courgette
      fonts:
        - asset: assets/fonts/Courgette-Regular.ttf
    - family: Playball
      fonts:
        - asset: assets/fonts/Playball-Regular.TTF

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
